# Generated by Django 5.1.6 on 2025-02-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dash", "0003_rename_role_userinfo_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=10)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
