# Generated by Django 5.1.6 on 2025-02-14 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Dash", "0004_logentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogEntry",
        ),
    ]
